from __future__ import annotations

import argparse
import asyncio
from pathlib import Path
from uuid import uuid4

from app.catalog import Catalog
from app.chat_model import build_chat_model
from app.config import describe_vector_store, settings, short_path
from app.rag_graph import (
    build_graph,
    get_thread_state,
    thread_config,
    unique_sources,
)
from app.scope import build_scoped_retriever, resolve_scope


async def run_chat(
    *,
    category: str | None = None,
    document: str | None = None,
    documents: list[str] | None = None,
    documents_dir: Path | None = None,
    db_path: Path | None = None,
) -> None:
    documents_dir = Path(documents_dir or settings.documents_dir)
    db_path = Path(db_path or settings.catalog_db_path)

    try:
        scope = resolve_scope(
            Catalog(db_path, create=False),
            config=settings,
            category=category,
            document=document,
            documents=documents or [],
        )
        # A scope is a different retriever handed to the same graph, which is why
        # the graph itself is untouched by any of this.
        graph = build_graph(
            chat_model=build_chat_model(),
            retriever=build_scoped_retriever(scope),
        )
    except (LookupError, RuntimeError) as exc:
        # A key that is missing, a category that is not there: a message to read,
        # not a stack trace to work through.
        raise SystemExit(str(exc)) from exc

    # A console session is not resumed: its history is worth a run, not a file.
    config = thread_config(f"console-{uuid4()}")

    print("Repertorio Docs console")
    # The console reads the same `.env` as the sync, but saying which store it
    # ended up on costs a line and answers the first question a wrong answer
    # raises. Same for the scope: a question asked of three documents rather than
    # the library answers differently, and the difference is not visible from the
    # question.
    print(f"store: {describe_vector_store(settings)}")
    print(f"catalog: {short_path(db_path)}")
    print(f"scope: {scope.label}")
    print("Type 'exit' to quit.\n")

    while True:
        try:
            question = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not question:
            continue
        if question.lower() in {"exit", "quit"}:
            break

        print("Assistant: ", end="", flush=True)

        try:
            async for chunk in graph.astream(
                {
                    "messages": [
                        {
                            "role": "user",
                            "content": question,
                        }
                    ]
                },
                config=config,
                stream_mode="messages",
                version="v2",
            ):
                if chunk["type"] != "messages":
                    continue

                token, metadata = chunk["data"]

                # Most messages emitted here are token chunks. We only display
                # tokens generated by the final answer node.
                if metadata.get("langgraph_node") != "answer":
                    continue

                content = token.content
                if isinstance(content, str):
                    print(content, end="", flush=True)

            print("\n")

            state = get_thread_state(config, graph)
            sources = unique_sources(state.values.get("retrieved_documents", []))

            if sources:
                print("Sources:")
                for source in sources:
                    page = source.get("page")
                    suffix = f" - p. {page}" if page else ""
                    print(f"  - {source.get('source')}{suffix}")
                print()

        except Exception as exc:  # noqa: BLE001
            # A failed question ends the question, not the console.
            print(f"\nError: {exc}\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Ask questions about the library. Without a scope, the whole library "
            "is searched; with one, only what it names."
        )
    )
    parser.add_argument(
        "--category",
        metavar="NAME",
        help="ask only about a category and what is filed below it; '' for the "
        "documents in no category",
    )
    parser.add_argument(
        "--document",
        metavar="PATH",
        help="ask only about one document, read whole when it is small enough",
    )
    parser.add_argument(
        "--documents",
        nargs="+",
        metavar="PATH",
        help="ask only about these documents, searched by similarity",
    )
    parser.add_argument(
        "--documents-dir",
        type=Path,
        default=settings.documents_dir,
        help="folder to watch (default: %(default)s)",
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=settings.catalog_db_path,
        help="catalog database (default: %(default)s)",
    )

    args = parser.parse_args()

    # `--documents` takes several values, so argparse cannot be asked to make
    # these exclusive; said here instead.
    given = [
        name
        for name, was_given in (
            ("--category", args.category is not None),
            ("--document", args.document is not None),
            ("--documents", bool(args.documents)),
        )
        if was_given
    ]
    if len(given) > 1:
        parser.error("give one of " + ", ".join(given) + ", not several")

    return args


def main() -> None:
    args = parse_args()
    asyncio.run(
        run_chat(
            category=args.category,
            document=args.document,
            documents=args.documents,
            documents_dir=args.documents_dir,
            db_path=args.db,
        )
    )


if __name__ == "__main__":
    main()
