from __future__ import annotations

import asyncio
from uuid import uuid4

from app.rag_graph import app, get_thread_state


async def run_chat() -> None:
    thread_id = f"console-{uuid4()}"
    config = {"configurable": {"thread_id": thread_id}}

    print("Repertorio Docs console")
    print("Type 'exit' to quit.\n")

    while True:
        try:
            question = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            break

        if not question:
            continue
        if question.lower() in {"exit", "quit"}:
            break

        print("Assistant: ", end="", flush=True)

        try:
            async for chunk in app.astream(
                {
                    "messages": [
                        {
                            "role": "user",
                            "content": question,
                        }
                    ]
                },
                config=config,
                stream_mode="messages",
                version="v2",
            ):
                if chunk["type"] != "messages":
                    continue

                token, metadata = chunk["data"]

                # Most messages emitted here are token chunks. We only display
                # tokens generated by the final answer node.
                if metadata.get("langgraph_node") != "answer":
                    continue

                content = token.content
                if isinstance(content, str):
                    print(content, end="", flush=True)

            print("\n")

            state = get_thread_state(config)
            sources = state.values.get("retrieved_documents", [])

            if sources:
                unique_sources = []
                seen = set()
                for source in sources:
                    key = (source.get("source"), source.get("page"))
                    if key not in seen:
                        seen.add(key)
                        unique_sources.append(source)

                print("Sources:")
                for source in unique_sources:
                    page = source.get("page")
                    suffix = f" - p. {page}" if page else ""
                    print(f"  - {source.get('source')}{suffix}")
                print()

        except Exception as exc:  # noqa: BLE001
            # A failed question ends the question, not the console.
            print(f"\nError: {exc}\n")


if __name__ == "__main__":
    asyncio.run(run_chat())
